# /bin/bash
# what is needed on the cluster...

[root@s54-1:/packages/6x/build/mapdamage/2.0.0]# module list
Currently Loaded Modulefiles:
  1) gcc/4.9.3      2) java/latest    3)         4) curl/7.49.1    5) python/2.7.6


yum install gsl-devel.x86_64  # appears to be on the cluster for 6x...

# I have to install the following...
module load python/2.7.6
module load r/3.2.5
# R installs:
install.packages("inline")
install.packages("gam")
install.packages("Rcpp")
install.packages("ggplot2")
install.packages("RcppGSL")

# python installs:
pip install pysam

cd /packages/6x/
mkdir mapdamage/2.0.0
cd mapdamage/2.0.0

git clone https://github.com/ginolhac/mapDamage.git .
python setup.py install



mapDamage2 is a computational framework written in Python and R, which tracks and quantifies DNA damage patterns among ancient DNA sequencing reads generated by Next-Generation Sequencing platforms.  mapDamage is developed at the Centre for GeoGenetics by the Orlando Group.

